return {
    'main',
    'db',
    'support',
    'models/model',
    'models/category',
    'models/person',
    'models/delivery',
    'models/delivery_category',
    'models/delivery_person',
    'commands',
    'interface',
    'interface/commands',
    'interface/persons',
    'interface/deliveries',
    'interface/categories',
    'interface/reports',
}